name: Build and Release

on:
  push:
    tags:
      - 'v*' # This will trigger on any tag that starts with 'v'

# Add this permissions block
permissions:
  contents: write  # This is crucial for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Create ZIP archive
        run: |
          cd out
          zip -r ../portfolio-build.zip .
          cd ..
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: portfolio-build.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true